import {
  LayoutDashboard,
  HeartPulse,
  Baby,
  BedDouble,
  Users,
  Stethoscope,
  PhoneCall,
  BarChart3,
  UtensilsCrossed,
  IdCard,
  FileSignature,
  GraduationCap,
  MessageCircle,
  Settings,
  type LucideIcon,
} from "lucide-react";

export const MODULE_ICONS: Record<string, LucideIcon> = {
  "1": LayoutDashboard,
  "2": HeartPulse,
  "3": Baby,
  "4": BedDouble,
  "5": Users,
  "6": Stethoscope,
  "7": PhoneCall,
  "8": BarChart3,
  "9": UtensilsCrossed,
  "10": IdCard,
  "12": FileSignature,
  "13": GraduationCap,
  "14": MessageCircle,
  "15": Settings,
};
